// Generated by https://quicktype.io

export interface NewsResponse {
    status:       string;
    totalResults: number;
    articles:     Article[];
}

export interface Article {
    source:         Source;
    author?:        string; //cambiamos un poco estas líneas
    title:          string;
    description?:   string;
    url:            string;
    urlToImage?:    string;
    publishedAt:    string;
    content?:       string;
}

export interface Source {
    id?:    string;
    name:   string;
}

//creamos esta interface que me va a servir para poder tipar la interface en "news.service.ts"
export interface ArticlesByCategoryAndPage {
    [key: string] : {
        page: number,
        articles: Article[]
    }
}